---
- hosts: all
  vars:
    jboss_home: /opt/jboss-as/jboss-eap-7.1
    files_cli:
      - { file: 'change-bind.cli'}
      - { file: 'reload.cli'}
  tasks:
    - name: Copy files for cli execution
      copy:
        src: "{{item.file}}"
        dest: "{{jboss_home}}/bin/{{item.file}}"
      with_items: "files_cli"

    - name: Expose management console and reload
      command:
        "{{jboss_home}}/bin/jboss-cli.sh --connect --file={{item.file}}"
      with_items: "{{files_cli}}"
