---
- hosts: all
  vars:
    jboss_home: /opt/jboss-as/jboss-eap-7.1
    files_cli:
      - change-bind.cli
      - reload.cli
  tasks:
    - name: Copy files for cli execution
      copy:
        src: {{item}}
        dest: {{jboss_home}}/bin/{{item}}
      loop: "files_cli"

    - name: Expose management console and reload
      command:
        "{{jboss_home}}/bin/jboss-cli.sh --connect --file={{item}}"
      loop: "{{files_cli}}"
