---
- hosts: all
  vars:
    jboss_home: /opt/jboss-as/jboss-eap-7.1
    files_cli:
      - change-bind.cli
      - reload.cli
  tasks:
    - name: Expose management console and reload
      command:
        "{{jboss_home}}/bin/jboss-cli.sh --connect --file={{item.value}}"
      loop: "{{files_cli}}"
